name: Lint-Build-Test
on: push

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'
      - name: Lint Python code
        uses: astral-sh/ruff-action@v3
        with:
          src: "./app"
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
