name: Lint-Build-Test
on:
  [push, pull_request]
permissions: read-all

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install python
        run: uv python install
      - name: Lint Python code
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b
        with:
          src: "./app"
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
        with:
          dockerfile: ./Dockerfile
          no-fail: false
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest
      - name: Build Dockerfile
        run: docker build -t hivebox:v0.0.1 .
