name: Lint-Build-Test
on:
  [push, pull_request]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install python
        run: uv python install
      - name: Lint Python code
        uses: astral-sh/ruff-action@v3
        with:
          src: "./app"
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ./Dockerfile
          no-fail: false
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest
      - name: Build Dockerfile
        run: docker build -t hivebox:v0.0.1 .
